apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: controller
  namespace: kong
spec:
  chart:
    spec:
      chart: kong
      version: '2.6.4'
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  interval: 1m0s
  targetNamespace: kong
  install:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
    podAnnotations:
      linkerd.io/inject: enabled
    manager:
      enabled: false
    portal:
      enabled: false
    portalapi:
      enabled: false
    status:
      enabled: false
    proxy:
      enabled: false
    deployment:
      kong:
        enabled: false
    ingressController:
      env:
        kong_admin_url: "http://kong-proxy-kong-admin:8001"
        publish_service: "kong/kong-proxy-kong-proxy"
    