apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: proxy
  namespace: kong
spec:
  chart:
    spec:
      chart: kong
      version: '2.6.4'
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  interval: 1m0s
  targetNamespace: kong
  install:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
    podAnnotations:
      linkerd.io/inject: ingress
    ingressController:
      enabled: false
    admin:
      enabled: true
      type: ClusterIP
      http:
        enabled: true
      tls:
        enabled: false